# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3dc715e20273b2c18a206062b623f371216f2792e832e19c1c0cada15279a776ede80f94e18a0ed7b8be231665e10786c9dc8a8df8eb4065bf04f39f76785f1b

test:
  secret_key_base: 95189e956d5a4aa2ca7d28661c76ddc75e90ca0275e3511c239fd13fa0535753adca38d8766063d884a489f2d3cdef61129223160a71d528adc2febd1a4e8066

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
